revert

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -292,15 +292,24 @@ jobs:
 
       - name: Update feeds Package
         run: |
-          cd openwrt && ./scripts/feeds update -a -f
+          file=./scripts/data/feeds_update.txt
+          while read -r line; do
+          cd openwrt && ./scripts/feeds update $line
+          done < "$file"
 ### ----------------------------------------------------------------- ###
       - name: Install feeds Package
         run: |
-          cd openwrt && ./scripts/feeds install -a -f
+          file=./scripts/data/feeds_install.txt
+          while read -r line; do
+          cd openwrt && ./scripts/feeds install $line
+          done < "$file"
 ### ----------------------------------------------------------------- ###
       - name: Uninstall feeds Package
         run: |
-          cd openwrt && ./scripts/feeds uninstall bluld
+          file=./scripts/data/feeds_uninstall.txt
+          while read -r line; do
+          cd openwrt && ./scripts/feeds uninstall $line
+          done < "$file"
 ### ----------------------------------------------------------------- ###
       - name: Developer (English language Only)
         id: po-english
@@ -612,82 +621,84 @@ jobs:
         run: |
           cd openwrt
           make download -j50
+          find dl -size -1024c -exec ls -l {} \;
+          find dl -size -1024c -exec rm -f {} \;
 ### ----------------------------------------------------------------- ###
-#      - name: Make
-#        id: GNUTAR
-#        run: |
-#          df -h
-#          cd openwrt
-#          let make_process=$(nproc)+2
-#          make -j${make_process} V=s
+      - name: Building and installing GNU tar
+        id: GNUTAR
+        run: |
+          df -h
+          cd openwrt
+          let make_process=$(nproc)+2
+          make tools/tar/compile -j${make_process} V=s
 ### ----------------------------------------------------------------- ###
-#      - name: Building and installing tools
-#        id: maketools
-#        run: |
-#          df -h
-#          cd openwrt
-#          let make_process=$(nproc)+2
-#          make tools/install -j${make_process} V=s
+      - name: Building and installing tools
+        id: maketools
+        run: |
+          df -h
+          cd openwrt
+          let make_process=$(nproc)+2
+          make tools/install -j${make_process} V=s
 ### ----------------------------------------------------------------- ###
-#      - name: Building and installing toolchain
-#        id: maketoolchain
-#        run: |
-#          df -h
-#          cd openwrt
-#          let make_process=$(nproc)+2
-#          make toolchain/install -j${make_process} V=s
+      - name: Building and installing toolchain
+        id: maketoolchain
+        run: |
+          df -h
+          cd openwrt
+          let make_process=$(nproc)+2
+          make toolchain/install -j${make_process} V=s
 ### ----------------------------------------------------------------- ###
-#     - name: Building kmods
-#       id: makekmods
-#       if: env.BUILD_KMODS == 'true' && !cancelled()
-#       run: |
-#         df -h
-#         cd openwrt
-#         let make_process=$(nproc)+2
-#         make target/compile -j${make_process} V=s
+      - name: Building kmods
+        id: makekmods
+        if: env.BUILD_KMODS == 'true' && !cancelled()
+        run: |
+          df -h
+          cd openwrt
+          let make_process=$(nproc)+2
+          make target/compile -j${make_process} V=s
 ### ----------------------------------------------------------------- ###
-#      - name: Building packages
-#        id: makepackages
-#        if: env.BUILD_PACKAGES == 'true' && !cancelled()
-#        run: >
-#          df -h
-#
-#          cd openwrt
-#
-#          let make_process=$(nproc)+2
-#
-#          make package/compile -j${make_process} || make package/compile
-#          -j${make_process} V=s 2>&1 | tee logs/build.log | grep -i -E
-#          "^make.*(error|[12345]...Entering directory)"
-### ----------------------------------------------------------------- ###
-#      - name: Installing packages
-#        id: installpackages
-#        if: env.INSTALL_PACKAGES == 'true' && !cancelled()
-#        run: >
-#          df -h
-#
-#          cd openwrt
-#
-#          let make_process=$(nproc)+2
-#
-#          make package/install -j${make_process} || make package/install
-#          -j${make_process} V=s 2>&1 | tee logs/build.log | grep -i -E
-#          "^make.*(error|[12345]...Entering directory)"
-### ----------------------------------------------------------------- ###
-#      - name: Indexing packages
-#        id: indexingpackages
-#        if: env.INDEX_PACKAGES == 'true' && !cancelled()
-#        run: >
-#          df -h
+      - name: Building packages
+        id: makepackages
+        if: env.BUILD_PACKAGES == 'true' && !cancelled()
+        run: >
+          df -h
 
-#          cd openwrt
+          cd openwrt
 
-#          let make_process=$(nproc)+2
+          let make_process=$(nproc)+2
 
-#          make package/index -j${make_process} CONFIG_SIGNED_PACKAGES= || make
-#          package/index -j${make_process} CONFIG_SIGNED_PACKAGES= V=s 2>&1 | tee
-#          logs/build.log | grep -i -E "^make.*(error|[12345]...Entering
-#          directory)"
+          make package/compile -j${make_process} || make package/compile
+          -j${make_process} V=s 2>&1 | tee logs/build.log | grep -i -E
+          "^make.*(error|[12345]...Entering directory)"
+### ----------------------------------------------------------------- ###
+      - name: Installing packages
+        id: installpackages
+        if: env.INSTALL_PACKAGES == 'true' && !cancelled()
+        run: >
+          df -h
+
+          cd openwrt
+
+          let make_process=$(nproc)+2
+
+          make package/install -j${make_process} || make package/install
+          -j${make_process} V=s 2>&1 | tee logs/build.log | grep -i -E
+          "^make.*(error|[12345]...Entering directory)"
+### ----------------------------------------------------------------- ###
+      - name: Indexing packages
+        id: indexingpackages
+        if: env.INDEX_PACKAGES == 'true' && !cancelled()
+        run: >
+          df -h
+
+          cd openwrt
+
+          let make_process=$(nproc)+2
+
+          make package/index -j${make_process} CONFIG_SIGNED_PACKAGES= || make
+          package/index -j${make_process} CONFIG_SIGNED_PACKAGES= V=s 2>&1 | tee
+          logs/build.log | grep -i -E "^make.*(error|[12345]...Entering
+          directory)"
 ### ----------------------------------------------------------------- ###
       - name: Build Firmware (OpenWRT)
         id: compile
@@ -696,7 +707,8 @@ jobs:
           cd openwrt
           echo -e "$(nproc) thread compile"
           let Make_Process=$(nproc)+2
-          make -j${Make_Process} V=s
+          make -j${Make_Process} target/install || make -j${Make_Process} target/install V=s
+          echo $?
           echo "::set-output name=status::success"
 ### --------------------------- ###
       - name: If Error (Build Firmware)
@@ -707,62 +719,62 @@ jobs:
           name: 'OpenWrt_logs${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}'
           path: openwrt/logs/
 ### ----------------------------------------------------------------- ###
-#     - name: Generate Buildinfo (OpenWRT)
-#       id: buildinfo
-#       continue-on-error: true
-#       run: |
-#         cd openwrt
-#         echo -e "$(nproc) thread compile"
-#         let Make_Process=$(nproc)+2
-#         make buildinfo V=s
-#         echo $?
-#         echo "::set-output name=status::success"
+      - name: Generate Buildinfo (OpenWRT)
+        id: buildinfo
+        continue-on-error: true
+        run: |
+          cd openwrt
+          echo -e "$(nproc) thread compile"
+          let Make_Process=$(nproc)+2
+          make buildinfo V=s
+          echo $?
+          echo "::set-output name=status::success"
 ### --------------------------- ###
-#     - name: If Error (Generate Buildinfo)
-#       uses: actions/upload-artifact@main
-#       if: steps.buildinfo.outcome == 'failure'
-#           && env.UPLOAD_BUILD_LOGS == 'true'
-#       with:
-#         name: 'OpenWrt_logs${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}'
-#         path: openwrt/logs/
+      - name: If Error (Generate Buildinfo)
+        uses: actions/upload-artifact@main
+        if: steps.buildinfo.outcome == 'failure'
+            && env.UPLOAD_BUILD_LOGS == 'true'
+        with:
+          name: 'OpenWrt_logs${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}'
+          path: openwrt/logs/
 ### ----------------------------------------------------------------- ###
-#      - name: Generate JSON Overview (OpenWRT)
-#        id: overview
-#        continue-on-error: true
-#        run: |
-#          cd openwrt
-#          echo -e "$(nproc) thread compile"
-#          let Make_Process=$(nproc)+2
-#          make json_overview_image_info V=s
-#          echo $?
-#          echo "::set-output name=status::success"
+      - name: Generate JSON Overview (OpenWRT)
+        id: overview
+        continue-on-error: true
+        run: |
+          cd openwrt
+          echo -e "$(nproc) thread compile"
+          let Make_Process=$(nproc)+2
+          make json_overview_image_info V=s
+          echo $?
+          echo "::set-output name=status::success"
 ### --------------------------- ###
-#      - name: If Error (Generate JSON Overview)
-#        uses: actions/upload-artifact@main
-#        if: steps.overview.outcome == 'failure'
-#            && env.UPLOAD_BUILD_LOGS == 'true'
-#        with:
-#          name: 'OpenWrt_logs${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}'
-#          path: openwrt/logs/
+      - name: If Error (Generate JSON Overview)
+        uses: actions/upload-artifact@main
+        if: steps.overview.outcome == 'failure'
+            && env.UPLOAD_BUILD_LOGS == 'true'
+        with:
+          name: 'OpenWrt_logs${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}'
+          path: openwrt/logs/
 ### ----------------------------------------------------------------- ###
-#      - name: Generate HASH (OpenWRT)
-#        id: hash
-#        continue-on-error: true
-#        run: |
-#          cd openwrt
-#          echo -e "$(nproc) thread compile"
-#          let Make_Process=$(nproc)+2
-#          make checksum V=s
-#          echo $?
-#          echo "::set-output name=status::success"
+      - name: Generate HASH (OpenWRT)
+        id: hash
+        continue-on-error: true
+        run: |
+          cd openwrt
+          echo -e "$(nproc) thread compile"
+          let Make_Process=$(nproc)+2
+          make checksum V=s
+          echo $?
+          echo "::set-output name=status::success"
 ### --------------------------- ###
-#      - name: If Error (Generate HASH)
-#        uses: actions/upload-artifact@main
-#        if: steps.hash.outcome == 'failure'
-#            && env.UPLOAD_BUILD_LOGS == 'true'
-#        with:
-#          name: 'OpenWrt_logs${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}'
-#          path: openwrt/logs/
+      - name: If Error (Generate HASH)
+        uses: actions/upload-artifact@main
+        if: steps.hash.outcome == 'failure'
+            && env.UPLOAD_BUILD_LOGS == 'true'
+        with:
+          name: 'OpenWrt_logs${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}'
+          path: openwrt/logs/
 ### ----------------------------------------------------------------- ###
       - name: OpenWRT Variable Setups
         id: VBS
